version: "3.8"

services:
  galah:
    image: galah
    container_name: galah-container
    volumes:
      - ./logs:/galah/logs
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/galah/honeypot.json
    ports:
      - "80:8080"
      - "8080:8080"
      - "443:8443"
    command: >
      -o logs/galah.json
      -p gcp-vertex
      -m gemini-1.5-flash
      --cloud-project <PROJECT_ID>
      --cloud-location <LOCATION>
